### ISSUE TITLE
ValueError when parsing education, job area and work experience

### ISSUE THREAD

**Issue by solarfresh** [solarfresh/jobhunt#3]
job-list-intro might not contain education, job area or work experience

```
[2020-10-10 15:25:39,368] {{logging_mixin.py:112}} WARNING - 2020-10-10 15:25:39 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.104.com.tw/jobs/search/?ro=0&keyword=%E5%AF%86%E7%A2%BC%E5%AD%B8&jobsource=2018indexpoc&order=11&asc=0&page=1> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/scrapy/utils/defer.py", line 120, in iter_errback
    yield next(it)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/utils/python.py", line 347, in __next__
    return next(self.data)
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spidermiddlewares/referer.py", line 340, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.7/dist-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.7/dist-packages/scrapy/core/spidermw.py", line 64, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/airflow/plugins/crawler/spiders/job104.py", line 55, in parse
    area, exp, edu = article.css('div ul.job-list-intro li')
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by solarfresh** [comment]
It happens when the job is the piecework, and it will be ignored.

```
 【接案】人工智慧報導編譯
104外包網
不拘經歷不拘
種常見的評估指標》http://highscope.ch.ntu.edu.tw/wordpress/?p=80752 2. 《輕量加密、同態加密與區塊鏈：新世代密碼學的三大聖杯》http://highscope.ch.ntu.edu.tw/
```
